/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AiComposeRouteImport } from './routes/ai-compose'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiComposeRoute = AiComposeRouteImport.update({
  id: '/ai-compose',
  path: '/ai-compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-compose': typeof AiComposeRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-compose': typeof AiComposeRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-compose': typeof AiComposeRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai-compose'
    | '/contacts'
    | '/deals'
    | '/settings'
    | '/tasks'
    | '/companies/$id'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai-compose'
    | '/contacts'
    | '/deals'
    | '/settings'
    | '/tasks'
    | '/companies/$id'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai-compose'
    | '/contacts'
    | '/deals'
    | '/settings'
    | '/tasks'
    | '/companies/$id'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiComposeRoute: typeof AiComposeRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-compose': {
      id: '/ai-compose'
      path: '/ai-compose'
      fullPath: '/ai-compose'
      preLoaderRoute: typeof AiComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiComposeRoute: AiComposeRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
